apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mysql-80-rhel7
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mysql-80-rhel7
    name: mysql-80-rhel7
    uid: c21278ce-8bf8-11e8-a514-080027f414e3
  spec:
    clusterIP: 172.30.0.30
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      app: mysql-80-rhel7
      deploymentconfig: mysql-80-rhel7
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: mysql-80-rhel7
  spec:
    replicas: 1
    selector:
      app: mysql-80-rhel7
      deploymentconfig: mysql-80-rhel7
    strategy:
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mysql-80-rhel7
          deploymentconfig: mysql-80-rhel7
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: myroot
          - name: MYSQL_PASSWORD
            value: myroot123
          - name: MYSQL_DATABASE
            value: mydjango
          image: registry.access.redhat.com/rhscl/mysql-80-rhel7
          imagePullPolicy: Always
          name: mysql-80-rhel7
          ports:
          - containerPort: 3306
            protocol: TCP